---
apiVersion: v1
kind: Service
metadata:
  name: greet-go-service
spec:
  type: LoadBalancer
  selector:
    app: greet-go-app      # This field will be replaced by the kustomize.
  ports:
    - name: http
      port: 3000
      targetPort: 8080
      protocol: TCP
