apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: unbound
namespace: unbound
resources:
- deployment.yaml
- service.yaml
configMapGenerator:
- name: unbound-conf
  files:
  - unbound.conf.d/unbound.conf
secretGenerator:
- name: certs
  files:
  - certs/ca-certificates.crt
