apiVersion: batch/v1
kind: CronJob
metadata:
  name: shell-cron-job
  labels:
    app: shell-cron-job
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: shell-cron-job
        spec:
          containers:
          - name: hello
            image: alpine:3.16
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
