apiVersion: v1
kind: Pod
metadata:
  name: ex-storage-empty-dir
spec:
  containers:
  - image: nginx:1.23
    name: nginx-container
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
