apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hello-app
spec:
  selector:
    matchLabels:
      app: go-hello-app
  replicas: 2
  template:
    metadata:
      labels:
        app: go-hello-app
    spec:
      containers:
      - name: go-hello-app
        image: go-hello-app:0.2
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-hello-service
spec:
  type: LoadBalancer
  selector:
    app: go-hello-app
  ports:
    - name: http
      port: 3000
      targetPort: 8080
      protocol: TCP
