apiVersion: v1
kind: Pod
metadata:
  name: greet-rust-pod
  labels:
    app: greet-rust-app
spec:
  containers:
  - name: greet-rust-app
    image: greet-rust:0.1
    imagePullPolicy: Never
    ports:
    - containerPort: 8080
    args:
    - "$(MY_POD_IP)"
    env:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: greet-rust-service
spec:
  type: LoadBalancer
  selector:
    app: greet-rust-app
  ports:
    - name: http
      port: 3000
      targetPort: 8080
      protocol: TCP
