apiVersion: apps/v1
kind: Deployment
metadata:
  name: greet-go-app
spec:
  selector:
    matchLabels:
      app: greet-go-app
  replicas: 2
  template:
    metadata:
      labels:
        app: greet-go-app
    spec:
      containers:
      - name: greet-go
        image: greet-go:0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: greet-go-service
spec:
  type: LoadBalancer
  selector:
    app: greet-go-app
  ports:
    - name: http
      port: 3000
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: greet-go-nodeport
spec:
  type: NodePort
  selector:
    app: greet-go-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000
