apiVersion: v1
kind: ConfigMap
metadata:
  namespace: python-cron-job
  name: python-cron-job-main
  labels:
    app: python-cron-job
data:
  main.py: |
    #!env python
    import datetime


    def main():
        """main"""
        print(datetime.datetime.now().strftime('%Y-%m-%dT%H:%M:%S'))
        print("Hello from the Kubernetes cluster")


    if __name__ == '__main__':
        main()
---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: python-cron-job
  name: python-cron-job
  labels:
    app: python-cron-job
spec:
  schedule: "* * * * *"
  concurrencyPolicy: "Forbid"
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: python-cron-job
        spec:
          restartPolicy: Never
          containers:
          - name: default
            image: python:3.8-slim-buster
            imagePullPolicy: IfNotPresent
            command: ["python", "/app/main.py"]
            volumeMounts:
            - mountPath: "/app"
              name: app-volume
              readOnly: true
          volumes:
          - name: app-volume
            configMap:
              name: python-cron-job-main
