apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  name: fruit-store-jdbc-api-sb
spec:
  service:
    apiVersion: v1
    kind: Secret
    name: postgres-client-sb
  workload:
    apiVersion: apps/v1
    kind: Deployment
    name: fruit-store-jdbc-api-dep
  env: # []EnvMapping, optional
  - name: PGUSER
    key: username
  - name: PGPASSWORD
    key: password
  - name: PGDATABASE
    key: database
  - name: PGHOST
    key: host
  - name: PGPORT
    key: port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fruit-store-jdbc-api-dep
  labels:
    app: fruit-store-jdbc-api
spec:
  selector:
    matchLabels:
      app: fruit-store-jdbc-api
  template:
    metadata:
      labels:
        app: fruit-store-jdbc-api
    spec:
      containers:
      - image: fruit-store-jdbc-api:0.0.1
        name: fruit-store-jdbc-api
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fruit-store-jdbc-api-service
spec:
  type: LoadBalancer
  selector:
    app: fruit-store-jdbc-api
  ports:
    - name: http
      port: 3000
      targetPort: 8080
      protocol: TCP
