#!/bin/bash
psql -U ${POSTGRES_USER} <<EOF
CREATE ROLE ${ADDITIONAL_USER} LOGIN PASSWORD '${ADDITIONAL_PASSWORD}';
CREATE DATABASE fruits OWNER ${ADDITIONAL_USER};
GRANT CONNECT ON DATABASE fruits to ${ADDITIONAL_USER};
GRANT ALL PRIVILEGES ON DATABASE fruits TO ${ADDITIONAL_USER};
\connect fruits;
CREATE SCHEMA IF NOT EXISTS ${ADDITIONAL_USER};
GRANT USAGE ON SCHEMA ${ADDITIONAL_USER} TO ${ADDITIONAL_USER};
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA ${ADDITIONAL_USER} TO ${ADDITIONAL_USER};
GRANT USAGE ON ALL SEQUENCES IN SCHEMA ${ADDITIONAL_USER} TO ${ADDITIONAL_USER};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ${ADDITIONAL_USER} TO ${ADDITIONAL_USER};
EOF