== Example of REST

=== Set up a new project

[source,console]
----
$ cargo new --bin greet-rust
     Created binary (application) `greet-rust` package
----

.References
* https://mkaz.blog/working-with-rust/command-line-args/[Command-line args | mkaz.blog ^] +
  rust command args optional arguments - Google 検索
* https://github.com/actix/actix-web[actix/actix-web: Actix Web is a powerful, pragmatic, and extremely fast web framework for Rust.^] +
  actix-web - Google 検索
* https://github.com/serde-rs/json[serde-rs/json: Strongly typed JSON library for Rust^] +
  rust json - Google Search
* https://qiita.com/Yoshihiro-Hirose/items/2426fe5199cb1ff74bd7[Rust で actix-web を使って REST API を実装していく - Qiita^] +
  rust rest api - Google 検索

=== Run server

[source,console]
----
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 2m 38s
     Running `target/debug/greet-rust`
----

[source,console]
----
$ curl http://localhost:8080/hello/John
{"message":"Hello John!"}
----

=== Build docker

. Remove old image (Optional)
+
[source,shell]
----
docker image ls --filter reference=greet-rust:0.1 --format '{{.ID}}' | xargs --no-run-if-empty docker rmi
----

. Build a docker image
+
[source,shell]
----
docker image build --tag greet-rust:0.1 .
----
+
----
$ docker image build --tag greet-rust:0.1 .
...
$ docker image ls --filter reference=greet-rust
REPOSITORY   TAG       IMAGE ID       CREATED         SIZE
greet-rust   0.1       a0e11b1a25ba   5 minutes ago   16.8MB
----

=== Test docker image

. Create docker network
+
[source,shell]
----
docker network create --subnet=172.19.0.0/24 greet-net
----

. List and Show network settings
+
[source,shell]
----
(set -x;
 docker network ls --filter name=greet-net;
 docker network inspect greet-net --format '{{json .IPAM.Config}}')
----
+
[source,console]
----
$ (set -x;
 docker network ls --filter name=greet-net;
 docker network inspect greet-net --format '{{json .IPAM.Config}}')
+ docker network ls --filter name=greet-net
NETWORK ID     NAME        DRIVER    SCOPE
ca87ff4008aa   greet-net   bridge    local
+ docker network inspect greet-net --format '{{json .IPAM.Config}}'
[{"Subnet":"172.19.0.0/24"}]
----

. Get container ip
+
[source,shell]
----
CONTAINER_IP="172.19.0.100"
----

. Run docker
+
[source,shell]
----
docker run --name greet-rust -p 8080:8080 --rm -d --net=greet-net --ip=${CONTAINER_IP} greet-rust:0.1 "${CONTAINER_IP}"
----
+
[source,shell]
----
docker container ls --filter name=greet-rust
----
+
[source,shell]
----
docker ps --filter name=greet-rust
----

. Request to docker
+
--
* Request to localhost
+
[source,shell]
----
curl -s http://127.0.0.1:8080/hello/John | python3 -m json.tool
----
+
[source,json]
.Outputs
----
{
    "message": "Hello John!"
}
----

* Request to bridge docker network
+
[source,shell]
----
CONTAINER_IP=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' greet-rust)
curl -s http://${CONTAINER_IP}:8080/hello/John | python3 -m json.tool
----
+
[source,json]
.Outputs
----
{
    "message": "Hello John!"
}
----
--

. Stop docker and Remove bridge network
+
[source,shell]
----
(set -x; docker stop greet-rust; docker network rm greet-net)
----

==== Docker compose

. Install Docker Compose V2
+
[source,shell]
----
sudo apt-get install docker-compose-plugin
----

. Start docker container
+
----
$ docker compose up -d
Creating network "greet-rust_greet-net" with driver "bridge"
Creating greet-rust ... done
----

. Request to docker
+
[source,console]
----
$ curl -s http://127.0.0.1:8080/hello/John | python3 -m json.tool
{
    "message": "Hello John!"
}

$ docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' greet-rust
172.19.0.100

$ curl -s http://172.19.0.100:8080/hello/John | python3 -m json.tool
{
    "message": "Hello John!"
}
----

. Remove docker container
+
[source,console]
----
$ docker compose down
Stopping greet-rust ... done
Removing greet-rust ... done
Removing network greet-rust_greet-net
----

=== Deploy

. Push to KIND
+
[source,console]
----
$ kind --name kind-1 load docker-image greet-rust:0.1
Image: "greet-rust:0.1" with ID "sha256:4747b036d01caf7eac0bc110de70fac0fd1d8c18fffc1ca081e1416a4fe7c890" not yet present on node "kind-1-control-plane", loading...
----
+
[source,console]
----
$ kind get nodes --name kind-1
kind-1-control-plane
kind-1-worker
$ docker exec -it kind-1-control-plane crictl images
IMAGE                                      TAG                  IMAGE ID            SIZE
...
docker.io/library/greet-rust               0.1                  4747b036d01ca       14.2MB
...
$ docker exec -it kind-1-worker crictl images
----

. Deploy
+
[source,console]
----
$ kubectl apply -f ../greet-rust.pod.yaml
pod/greet-rust-pod created
service/greet-rust-service created
$ kubectl get service greet-rust-service
NAME                 TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)          AGE
greet-rust-service   LoadBalancer   10.96.19.233   172.18.254.240   3000:30763/TCP   28s
$ kubectl logs greet-rust-pod
server is listening on 10.244.0.7:8080 port
----

. Test
+
[source,console]
----
$ curl -s http://172.18.254.243:3000/hello/John | python3 -m json.tool
{
    "message": "Hello John!"
}
$ curl -s http://$(kubectl get services greet-rust-service -o jsonpath='{.status.loadBalancer.ingress[*].ip}'):$(kubectl get services greet-rust-service -o jsonpath='{.spec.ports[0].port}')/hello/John --header "Content-Type: application/json" | python3 -m json.tool
{
    "message": "Hello John!"
}
----

. Remove apps
+
[source,shell]
----
kubectl delete -f ../greet-rust.pod.yaml
----
+
[source,console]
----
$ kubectl delete -f ../greet-rust.pod.yaml
pod "greet-rust-pod" deleted
service "greet-rust-service" deleted
----

. Remove image in kind-1
+
[source,shell]
----
KIND_NODE="kind-1-worker"
docker exec -it "${KIND_NODE}" crictl images
docker exec -it "${KIND_NODE}" crictl rmi $(docker exec -it "${KIND_NODE}" crictl images -o json | jq '.images[] | select(.repoTags[] | contains("rust")) | .id' -r | sed -e 's/^sha256:\(........\).*/\1/')

KIND_NODE="kind-1-control-plane"
docker exec -it "${KIND_NODE}" crictl images
docker exec -it "${KIND_NODE}" crictl rmi $(docker exec -it "${KIND_NODE}" crictl images -o json | jq '.images[] | select(.repoTags[] | contains("rust")) | .id' -r | sed -e 's/^sha256:\(........\).*/\1/')
----

. Remove docker images (Optional)
+
[source,shell]
----
docker image ls --filter reference=greet-rust:0.1 --format '{{.ID}}' | xargs --no-run-if-empty docker rmi
----

=== Troubleshooting

==== curl: (56) Recv failure: Connection reset by peer
The first connection with the created Docker image failed.

----
$ curl -v http://127.0.0.1:8080/hello/John
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /hello/John HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.68.0
> Accept: */*
>
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
----

The problem was that the application listening loopback not `eth0`(172.17.0.2/16).

[source,console]
----
$ docker exec -it greet-rust /bin/sh
/opt/server # ls
greet-rust
/opt/server # ps
PID   USER     TIME  COMMAND
    1 root      0:00 ./greet-rust 127.0.0.1
   16 root      0:00 /bin/sh
   23 root      0:00 ps
/opt/server # curl
/bin/sh: curl: not found
/opt/server # ls
greet-rust
/opt/server # ls ..
server
/opt/server # ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
3: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
15: eth0@if16: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
    link/ether 02:42:ac:11:00:02 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.2/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever
/opt/server #
----
