== Example of Flask

=== Build docker image and run docker container

==== Using docker command

. Build docker.
+
[source,console]
----
$ docker image build --tag greet-python:0.1 .
----

. Run docker
+
[source,console]
----
$ docker run --name greet-python -p 8080:8080 --rm -d greet-python:0.1
----

==== Using docker-compose

. Run docker container:
+
[source,console]
----
$ docker-compose up --build -d
----

=== Test docker image

. Make sure the docker container is running
+
[source,shell]
----
docker container ls --filter name=greet-python
----
+
[source,console]
----
$ docker ps --filter name=greet-python
----

. Request to docker
+
[source,console]
----
$ curl http://127.0.0.1:8080/api/greet/John
{
  "message": "Hello, John!"
}
$ docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' greet-python
172.*.*.*
$ curl http://$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' greet-python):8080/api/greet/John
{
  "message": "Hello, John!"
}
----

. Stop and remove docker container

** Using docker
+
[source,console]
----
$ docker stop greet-python
----

** Using docker-compose
+
[source,console]
----
$ docker-compose down
----

=== Deploy

. Push to KIND
+
[source,console]
----
$ kind --name kind-1 load docker-image greet-python:0.1
Image: "greet-python:0.1" with ID "sha256:89a16e5c16a1fe123f1c3c0dbf8a1e7d026e5292b1a135e868660bba0ca070e0" not yet present on node "kind-1-control-plane", loading..
----
+
[source,console]
----
$ docker exec -it kind-1-control-plane crictl images | grep -E 'IMAGE ID|greet-python'
IMAGE                                      TAG                  IMAGE ID            SIZE
docker.io/library/greet-python             0.1                  89a16e5c16a1f       126MB
----

. Deploy
+
[source,console]
----
$ kubectl apply -f kind/greet-python.pod.yaml
pod/greet-python-pod created
service/greet-python-service created
$ kubectl get service greet-python-service
NAME                   TYPE           CLUSTER-IP    EXTERNAL-IP      PORT(S)          AGE
greet-python-service   LoadBalancer   10.96.11.59   172.18.254.240   3000:31186/TCP   13s
$ kubectl logs greet-python-pod
 * Serving Flask app 'server'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.244.0.7:8080
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 105-396-156
----

. Test
+
[source,console]
----
$ curl -s http://172.18.254.240:3000/api/greet/John
{
  "message": "Hello, John!"
}
$ curl -s http://$(kubectl get services greet-python-service -o jsonpath='{.status.loadBalancer.ingress[*].ip}'):$(kubectl get services greet-python-service -o jsonpath='{.spec.ports[0].port}')/api/greet/John --header "Content-Type: application/json" | python3 -m json.tool
{
    "message": "Hello, John!"
}
----

. Remove apps
+
[source,console]
----
$ kubectl delete -f kind/greet-python.pod.yaml
pod "greet-python-pod" deleted
service "greet-python-service" deleted
----

. Remove docker image from KIND
+
[source,console]
----
$ docker exec -it kind-1-control-plane crictl images | grep -E 'IMAGE ID|docker.io/library/greet-python'
...
$ docker exec kind-1-control-plane crictl images | grep -E 'docker.io/library/greet-python' | awk '{print $3}' | xargs --no-run-if-empty docker exec kind-1-control-plane crictl rmi
Deleted: docker.io/library/greet-python:0.1
----

=== Troubleshooting

==== Failed to connect to 127.0.0.1 port 8080: Connection refused

The solution: listen on all interfaces.

[source,diff]
.python-hello/src/server.py
----
@@ -12,4 +12,4 @@ def hello():


 if __name__ == "__main__":
-    app.run(debug=True, port=8080)
+    app.run(debug=True, host="0.0.0.0", port=8080)
----

[source,console]
----
$ docker run --name greet-python -p 8080:8080 --rm -d greet-python:0.1
...
$ curl http://127.0.0.1:8080/api/greet
curl: (7) Failed to connect to 127.0.0.1 port 8080: Connection refused
----

listen only localhost:8080.

[source,console]
----
$ docker exec -it greet-python /bin/bash
root@53cb8c0d4173:/# apt update
...
# apt install -y lsof curl net-tools iproute2
root@53cb8c0d4173:/# lsof -i -P | grep localhost
python    1 root    3u  IPv4 1275830      0t0  TCP localhost:8080 (LISTEN)
python    1 root    5u  IPv4 1275830      0t0  TCP localhost:8080 (LISTEN)
python    8 root    3u  IPv4 1275830      0t0  TCP localhost:8080 (LISTEN)
python    8 root    5u  IPv4 1275830      0t0  TCP localhost:8080 (LISTEN)
root@53cb8c0d4173:/# lsof -i -P | grep 172.17.0.2
root@53cb8c0d4173:/#
----

* 修正後
+
[source,console]
----
# apt update
...
# apt install -y lsof iproute2
# ip address show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
3: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
35: eth0@if36: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:11:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.17.0.2/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever
root@70aff0476f6b:/# lsof -i -P | grep python
python    1 root    3u  IPv4 1311491      0t0  TCP *:8080 (LISTEN)
python    1 root    5u  IPv4 1311491      0t0  TCP *:8080 (LISTEN)
python    8 root    3u  IPv4 1311491      0t0  TCP *:8080 (LISTEN)
python    8 root    5u  IPv4 1311491      0t0  TCP *:8080 (LISTEN)
----

==== kind: Failed to connect

[source,console]
----
$ curl -v http://172.18.254.240:3000/api/greet
*   Trying 172.18.254.240:3000...
* TCP_NODELAY set
* connect to 172.18.254.240 port 3000 failed: No route to host
* Failed to connect to 172.18.254.240 port 3000: No route to host
* Closing connection 0
curl: (7) Failed to connect to 172.18.254.240 port 3000: No route to host
$ kubectl get services greet-python-service
NAME                     TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)          AGE
greet-python-service   LoadBalancer   10.96.172.59   172.18.254.240   3000:30401/TCP   4m56s
$ kubectl get pods -l app=greet-python-app -o custom-column
s="Pod IP":.status.podIP,"Container port":.spec.containers[0].ports[].containerPort
Pod IP        Container port
10.244.0.15   8080
----

[source,console]
----
$ kubectl get endpoints greet-python-service
NAME                     ENDPOINTS   AGE
greet-python-service   <none>      6m31s
----

=== References

.Python
* https://hub.docker.com/_/python[python - Official Image | Docker Hub^] +
  alpine python - Google 検索
* https://www.docker.com/blog/containerized-python-development-part-1/[Containerized Python Development - Part 1 - Docker^] +
  python docker offline install "as builder" - Google Search
* https://blog.realkinetic.com/building-minimal-docker-containers-for-python-applications-37d0272c52f3[Building Minimal Docker Containers for Python Applications | by Nick Joyce | Real Kinetic Blog^] +
  python docker offline install "as builder" - Google Search
* https://future-architect.github.io/articles/20200513/[仕事でPythonコンテナをデプロイする人向けのDockerfile (1): オールマイティ編 | フューチャー技術ブログ^] +
  python alpine - Google 検索
* Apps
** https://rapidapi.com/blog/best-python-api-frameworks/[Top 15 Best Python REST API Frameworks (2022) | RapidAPI^] +
   python rest api server - Google Search


