apiVersion: v1
kind: Namespace
metadata:
  name: ex-job-with-cfm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fruits
  namespace: ex-job-with-cfm
data:
  fruits.txt: |
    apple
    banana
    cherry
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ex-job-with-cfm
  namespace: ex-job-with-cfm
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: busybox-pod
        image: busybox:1.34.1
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "for n in $(seq 60); do (set -x; echo n=$n; cat /fruits-volume/fruits.txt; sleep 3); done"]
        volumeMounts:
        - mountPath: "/fruits-volume"
          name: fruits-volume
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: fruits-volume
        configMap:
          name: fruits
