apiVersion: v1
kind: Pod
metadata:
  name: nginx-simple-env-new-app
  labels:
    app: nginx-simple-env-new-app
spec:
  containers:
  - name: default
    image: nginx:1.25.3
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080
    env: []  # Add environment variables by `kustomize`
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-simple-env-add-app
  labels:
    app: nginx-simple-env-add-app
spec:
  containers:
  - name: default
    image: nginx:1.25.3
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080
    env:
    - name: MY_ADD_ENV1
      value: "1"
    # Add environment variables by `kustomize`
