apiVersion: v1
kind: Pod
metadata:
  name: greet-python-pod
  labels:
    app: greet-python-app
spec:
  containers:
  - name: greet-python-app
    image: greet-python:0.1
    imagePullPolicy: Never
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: greet-python-service
spec:
  type: NodePort
  selector:
    app: greet-python-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000
