---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-simple-env-new-deployment
  labels:
    app: nginx-simple-env-new-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-simple-env-new-app
  template:
    metadata:
      name: nginx-simple-env-new-app
      labels:
        app: nginx-simple-env-new-app
    spec:
      containers:
      - name: default
        image: nginx:1.25.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env: []  # Add environment variables by `kustomize`
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-simple-env-add-deployment
  labels:
    app: nginx-simple-env-add-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-simple-env-add-app
  template:
    metadata:
      name: nginx-simple-env-add-app
      labels:
        app: nginx-simple-env-add-app
    spec:
      containers:
      - name: default
        image: nginx:1.25.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: MY_ADD_ENV1
          value: "1"
        # Add environment variables by `kustomize`
