apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "docker-registry"
  labels:
    app: docker-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1536Mi
  storageClassName: "slow"
  volumeName: "docker-registry"
