ifndef::leveloffset[]
:toc: left
:toclevels: 3
endif::[]

include::header.adoc[]

== Kind

* https://kind.sigs.k8s.io/[KIND^]
* https://github.com/kubernetes-sigs/kind[kubernetes-sigs/kind: Kubernetes IN Docker - local clusters for testing Kubernetes^]

=== Install KIND CLI

. Install golang and Set `go` bin path
+
[source,shell]
.~/.bashrc
----
cat >> ~/.bashrc <<'EOF'
export GOPATH=$HOME/go
test -d $GOPATH/bin && export PATH="$GOPATH/bin:$PATH"
EOF
----

. Apply changes
+
[source,shell]
----
exec $SHELL -l
----

. Install KIND
+
--
* Install by user
+
[source,shell]
----
sudo chown -R $USER:$GROUPS /home/guest/go
go install sigs.k8s.io/kind@v0.25.0
----

* Install by system
+
[source,shell]
----
[ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.25.0/kind-linux-amd64
sudo install ./kind /usr/local/bin/kind
rm -f ./kind
----
--
+
[NOTE]
.Failed to starting control-plane while running kind create cluster in KIND v0.20.0 on WSL2.
====
Probably due to insufficient memory in KIND v0.20.0 on WSL2.

[source,console]
----
$ go install sigs.k8s.io/kind@v0.25.0
go: downloading sigs.k8s.io/kind v0.25.0
...
$ kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.27.3) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✗ Starting control-plane 🕹️
Deleted nodes: ["kind-control-plane"]
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged kind-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 137
Command Output: I0812 15:25:35.842502      67 initconfiguration.go:255] loading configuration from "/kind/kubeadm.conf"
W0812 15:25:35.845911      67 initconfiguration.go:332] [config] WARNING: Ignored YAML document with GroupVersionKind kubeadm.k8s.io/v1beta3, Kind=JoinConfiguration
[init] Using Kubernetes version: v1.27.3
[certs] Using certificateDir folder "/etc/kubernetes/pki"
I0812 15:25:35.856822      67 certs.go:112] creating a new certificate authority for ca
----
====

. Check installed version
+
[source,console]
----
$ $(go env GOPATH)/bin/kind version
kind v0.25.0 go1.23.3 linux/amd64
----

=== Upgrade KIND CLI

. Upgrade KIND
+
[source,shell]
----
go install sigs.k8s.io/kind@v0.25.0
----

=== Creating a Cluster

==== Case 1: Install by default settings

. Create Cluster
+
[source,shell]
----
$(go env GOPATH)/bin/kind create cluster --name kind-1
----
+
[source,console]
.kind get clusters
----
$ kind get clusters
kind-1
----
+
[source,console]
.kubectl cluster-info --context kind-kind-1
----
$ kubectl cluster-info --context kind-kind-1
Kubernetes control plane is running at https://127.0.0.1:36897
CoreDNS is running at https://127.0.0.1:36897/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
----
+
[source,console]
.get nodes
----
$ kind get nodes --name ${KIND_CLUSTER_NAME:-kind-1}
kind-1-control-plane
kind-1-worker
----

==== Case 2: Using node port

https://kind.sigs.k8s.io/docs/user/using-wsl2/#accessing-a-kubernetes-service-running-in-wsl2[Accessing a Kubernetes Service running in WSL2^]

. Create KIND Cluster using YAML
+
[source,yaml]
.kind/kind-1.cluster.yaml
----
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-1
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
    protocol: TCP
----
+
[source,shell]
.Create KIND cluster
----
kind create cluster --config=kind/kind-1.cluster.yaml
----
+
[source,console]
.kind create cluster --config=kind/kind-1.cluster.yaml
----
$ $(go env GOPATH)/bin/kind create cluster --name kind-1
Creating cluster "kind-1" ...
 ✓ Ensuring node image (kindest/node:v1.25.3) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-kind-1"
You can now use your cluster with:

kubectl cluster-info --context kind-kind-1

Have a nice day! 👋
----
. Show settings
+
[source,console]
.WSL: ss -napt
----
$ ss -napt
State       Recv-Q   Send-Q     Local Address:Port      Peer Address:Port   Process
...
LISTEN      0        4096             0.0.0.0:30000          0.0.0.0:*
...
----
+
[source,console]
.Windows HOST: netstat -a
----
PS> netstat -a

アクティブな接続

  プロトコル  ローカル アドレス      外部アドレス           状態
  ...
  TCP         127.0.0.1:30000        DESKTOP-E39V4F4:0      LISTENING
  ...
----
+
[source,console]
.Windows HOST: Get-NetTCPConnection -LocalAddress 127.0.0.1 -LocalPort 30000
----
PS> Get-NetTCPConnection -LocalAddress 127.0.0.1 -LocalPort 30000

LocalAddress                        LocalPort RemoteAddress                       RemotePort State       AppliedSetting
------------                        --------- -------------                       ---------- -----       --------------
127.0.0.1                           30000     0.0.0.0                             0          Listen
----

.Testing
. Create deployment
+
[source,console]
.kubectl create deployment nginx --image=nginx --port=80
----
$ kubectl create deployment nginx --image=nginx --port=80
deployment.apps/nginx created
$ kubectl create service nodeport nginx --tcp=80:80 --node-port=30000
service/nginx created
----

. curl
+
[source,console]
.curl localhost:30000
----
$ curl localhost:30000
...
----

. Delete deployment
+
[source,console]
.kubectl delete deployment nginx
----
$ kubectl delete deployment nginx
deployment.apps "nginx" deleted
----

=== Using KIND CLI

* Get KIND clusters
+
[source,shell]
----
kind get clusters
----

* Get cluster certificate/context information
+
[source,shell]
----
kind get kubeconfig --name ${KIND_CLUSTER:-kind-1}
----

* Get cluster information

** Show API server URI
+
[source,shell]
----
kubectl cluster-info --context kind-${KIND_CLUSTER:--kind-1}
----

** Dump cluster information
+
[source,shell]
.Current context
----
kubectl cluster-info dump
----
+
[source,shell]
.Specific KIND context
----
kubectl cluster-info dump --context kind-${KIND_CLUSTER:--kind-1}
----

* Get KIND nodes
+
[source,shell]
----
kind get nodes --name ${KIND_CLUSTER:-kind-1}
----
+
[source,shell]
----
for KIND_CLUSTER in $(kind get clusters); do (set -x; kind get nodes --name ${KIND_CLUSTER}); done
----
+
[source,shell]
----
kind get clusters | while read KIND_CLUSTER; do (set -x; kind get nodes --name ${KIND_CLUSTER}); done
----

* List images
+
[source,shell]
----
docker exec -it ${KIND_NODENAME} crictl images
----
+
[source,shell]
----
for KIND_CLUSTER in $(kind get clusters); do for DOCKER_CONTAINER in $(kind get nodes --name ${KIND_CLUSTER}); do (set -x; docker exec ${DOCKER_CONTAINER} crictl images); done; done
----
+
[source,shell]
----
kind get clusters | while read KIND_CLUSTER; do kind get nodes --name ${KIND_CLUSTER} | while read DOCKER_CONTAINER; do (set -x; docker exec ${DOCKER_CONTAINER} crictl images); done; done
----

* Upload image to KIND
+
[source,shell]
----
kind load docker-image my-custom-image-0:tag1 my-custom-image-1:tag2 --name ${KIND_CLUSTER}
----

=== Install kubectl

.Make sure the version matches KIND.
* https://github.com/kubernetes-sigs/kind/releases[Releases · kubernetes-sigs/kind^]
+
> v0.20.0 Latest
> ...snip...
> *Breaking Changes*
> ...snip...
> - The default node image is a Kubernetes v1.27.3 image:

* https://kubernetes.io/releases/[Releases | Kubernetes^]


==== Install kubectl binary with curl on Linux
. Install kubectl
+
--
* Install specific version match to KIND (2023-11-01)
+
[source,shell]
----
KUBECTL_CLIENT_VERSION="v1.27.7"
curl --silent -L "https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_CLIENT_VERSION}/bin/linux/amd64/kubectl" > ~/bin/kubectl
chmod 755 ~/bin/kubectl
unset KUBECTL_CLIENT_VERSION
----

.Get latest release (not recommended)
. Download the latest release with the command: +
See: https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/[Install and Set Up kubectl on Linux | Kubernetes^]
+
[source,shell]
----
curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
----

. Validate the binary (optional)
+
[source,shell]
.Download the kubectl checksum file:
----
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
echo "$(cat kubectl.sha256) kubectl" | sha256sum --check
----
+
[source,shell]
.Validate the kubectl binary against the checksum file:
----
echo "$(cat kubectl.sha256) kubectl" | sha256sum --check
----

. Install kubectl
+
[source,shell]
----
install -m 0755 kubectl ~/bin/kubectl
rm kubectl
----
+
[source,shell]
----
sudo install -m 0755 kubectl /usr/local/bin/kubectl
rm kubectl
----
--

==== Install using native package management
. Update the apt package index and install packages needed to use the Kubernetes apt repository:
+
[source,shell]
----
sudo apt-get update
# apt-transport-https may be a dummy package; if so, you can skip that package
sudo apt-get install -y apt-transport-https ca-certificates curl
----

. Download the public signing key for the Kubernetes package repositories. The same signing key is used for all repositories so you can disregard the version in the URL:
+
--
* 1.27.x
[source,shell]
----
KUBECTL_CLIENT_VERSION="v1.27"
curl -fsSL https://pkgs.k8s.io/core:/stable:/${KUBECTL_CLIENT_VERSION}/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring-${KUBECTL_CLIENT_VERSION}.gpg
----
+
[source,shell]
.Add the appropriate Kubernetes apt repository.:
----
# This overwrites any existing configuration in /etc/apt/sources.list.d/kubernetes.list
echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring-${KUBECTL_CLIENT_VERSION}.gpg] https://pkgs.k8s.io/core:/stable:/${KUBECTL_CLIENT_VERSION}/deb/ /" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
----

* 1.28.x
+
[source,shell]
----
KUBECTL_CLIENT_VERSION="v1.28"
curl -fsSL https://pkgs.k8s.io/core:/stable:/${KUBECTL_CLIENT_VERSION}/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring-${KUBECTL_CLIENT_VERSION}.gpg
----
+
[source,shell]
.Add the appropriate Kubernetes apt repository. If you want to use Kubernetes version different than v1.28, replace v1.28 with the desired minor version in the command below:
----
# This overwrites any existing configuration in /etc/apt/sources.list.d/kubernetes.list
echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring-${KUBECTL_CLIENT_VERSION}.gpg] https://pkgs.k8s.io/core:/stable:/${KUBECTL_CLIENT_VERSION}/deb/ /" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
----
--

. Update apt package index, then install kubectl:
+
[source,shell]
----
sudo apt-get update
----
+
[source,shell]
.List available version
----
apt list -a kubectl --all-versions
----
+
--
* Install 1.27.x
+
[source,console]
----
$ sudo apt-cache showpkg kubectl | grep -F stable | grep -F '1.27.' | head -1
1.27.7-1.1 (/var/lib/apt/lists/pkgs.k8s.io_core:_stable:_v1.27_deb_Packages)
$ apt list -a kubectl | grep -w amd64 | grep -F '1.27' | sort -V | tail -1
kubectl/unknown 1.27.7-1.1 amd64
----
+
[source,shell]
----
sudo apt-get install -y kubectl=1.27.7-1.1
----

* Install latest version
+
[source,shell]
----
sudo apt-get install -y kubectl
----
--

=== arp/arping (optional)

[source,shell]
----
sudo apt install -y net-tools arping
----

=== Install MetalLB

https://metallb.universe.tf/installation/[MetalLB > Installation]

. Install MetalLB
+
[source,console]
----
$ kubectl apply -f kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.10/config/manifests/metallb-native.yaml
namespace/metallb-system created
customresourcedefinition.apiextensions.k8s.io/addresspools.metallb.io created
customresourcedefinition.apiextensions.k8s.io/bfdprofiles.metallb.io created
customresourcedefinition.apiextensions.k8s.io/bgpadvertisements.metallb.io created
customresourcedefinition.apiextensions.k8s.io/bgppeers.metallb.io created
customresourcedefinition.apiextensions.k8s.io/communities.metallb.io created
customresourcedefinition.apiextensions.k8s.io/ipaddresspools.metallb.io created
customresourcedefinition.apiextensions.k8s.io/l2advertisements.metallb.io created
serviceaccount/controller created
serviceaccount/speaker created
role.rbac.authorization.k8s.io/controller created
role.rbac.authorization.k8s.io/pod-lister created
clusterrole.rbac.authorization.k8s.io/metallb-system:controller created
clusterrole.rbac.authorization.k8s.io/metallb-system:speaker created
rolebinding.rbac.authorization.k8s.io/controller created
rolebinding.rbac.authorization.k8s.io/pod-lister created
clusterrolebinding.rbac.authorization.k8s.io/metallb-system:controller created
clusterrolebinding.rbac.authorization.k8s.io/metallb-system:speaker created
secret/webhook-server-cert created
service/webhook-service created
deployment.apps/controller created
daemonset.apps/speaker created
validatingwebhookconfiguration.admissionregistration.k8s.io/metallb-webhook-configuration created
----
+
[source,console]
----
$ kubectl get services -n metallb-system
NAME              TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE
webhook-service   ClusterIP   10.96.207.6   <none>        443/TCP   2m6s
$ kubectl get pods -n metallb-system
NAME                          READY   STATUS    RESTARTS   AGE
controller-84d6d4db45-pkq95   1/1     Running   0          2m25s
speaker-xxxxx                 1/1     Running   0          2m24s
----

. Get docker ip settings
+
[source,console]
----
$ docker network ls --filter name=kind
NETWORK ID     NAME      DRIVER    SCOPE
cb34625844b6   kind      bridge    local
----
+
[source,console]
----
$ docker network inspect kind --format '{{json .IPAM.Config}}' | python3 -m json.tool
[
    {
        "Subnet": "172.18.0.0/16",
        "Gateway": "172.18.0.1"
    },
    {
        "Subnet": "fc00:f853:ccd:e793::/64",
        "Gateway": "fc00:f853:ccd:e793::1"
    }
]
----

** https://kind.sigs.k8s.io/docs/user/loadbalancer/[kind - LoadBalancer^]

. Address pool settings.
+
[source,console]
----
$ kubectl apply -f kind/metallb-IPAddressPool.yaml
ipaddresspool.metallb.io/first-pool created
l2advertisement.metallb.io/l2-ad created
----
+
[source,yaml]
.metallb-IPAddressPool.yaml
----
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.18.254.240/28  # <1>
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-ad
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool
----
<1> DockerのIPを指定する

.References
* https://metallb.universe.tf/installation/[MetalLB, bare metal load-balancer for Kubernetes^]

=== Install Ingress

. Create Cluster +
Create a kind cluster with extraPortMappings and node-labels.
+
--
[horizontal]
extraPortMappings:: allow the local host to make requests to the Ingress controller over ports 80/443
node-labels:: only allow the ingress controller to run on a specific node(s) matching the label selector
--
+
[source,shell]
----
#!/bin/bash
cat <<EOF | kind create cluster --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
    protocol: TCP
  - containerPort: 30080
    hostPort: 30080
    protocol: TCP
  - containerPort: 30081
    hostPort: 30081
    protocol: TCP
EOF
----

. Install Contour
+
[source,shell]
----
kubectl apply -f https://projectcontour.io/quickstart/contour.yaml
----

. Apply it by running:
+
Apply kind specific patches to forward the hostPorts to the ingress controller, set taint tolerations and schedule it to the custom labelled node.
+
[source,json]
----
{
  "spec": {
    "template": {
      "spec": {
        "nodeSelector": {
          "ingress-ready": "true"
        },
        "tolerations": [
          {
            "key": "node-role.kubernetes.io/control-plane",
            "operator": "Equal",
            "effect": "NoSchedule"
          },
          {
            "key": "node-role.kubernetes.io/master",
            "operator": "Equal",
            "effect": "NoSchedule"
          }
        ]
      }
    }
  }
}
----
+
[source,shell]
----
kubectl patch daemonsets -n projectcontour envoy -p '{"spec":{"template":{"spec":{"nodeSelector":{"ingress-ready":"true"},"tolerations":[{"key":"node-role.kubernetes.io/control-plane","operator":"Equal","effect":"NoSchedule"},{"key":"node-role.kubernetes.io/master","operator":"Equal","effect":"NoSchedule"}]}}}}'
----

.References
* https://projectcontour.io/getting-started/[Getting Started with Contour^]
* https://tanzu.vmware.com/developer/guides/service-routing-contour-to-ingress-and-beyond/[Getting Started with Contour - To Ingress and Beyond | VMware Tanzu Developer Center^]

== Uninstall

. Remove docker image from KIND
+
[source,console]
----
$ docker exec -it kind-1-control-plane crictl images | grep -E 'IMAGE ID|your-image-name'
...
$ docker exec kind-1-control-plane crictl images | grep -E 'docker.io/library/your-image-name' | awk '{print $3}' | xargs --no-run-if-empty docker exec kind-1-control-plane crictl rmi
Deleted: docker.io/library/your-image-name
----

. Uninstall MetalLB
+
[source,shell]
----
kubectl delete -f greet-go-pod.yaml
kubectl delete -f https://raw.githubusercontent.com/metallb/metallb/v0.13.10/config/manifests/metallb-native.yaml
sudo arp -d 172.18.254.240
----

. Deleting a Cluster
+
[source,console]
----
$ kind get clusters
kind-1
$ kind delete cluster --name kind-1
Deleting cluster "kind-1" ...
$ arp -a
******* (172.31.160.1) at 00:15:5d:31:24:02 [ether] on eth0
----

.References
* MetalLB
** Address Pool 関連
*** https://thr3a.hatenablog.com/entry/20220718/1658127951[MetalLB v0.13以降はConfigmapでの設定ができない - 動かざることバグの如し]
*** https://metallb.universe.tf/configuration/_advanced_ipaddresspool_config/[MetalLB > ADVANCED ADDRESSPOOL CONFIGURATION]
*** https://github.com/metallb/metallb/issues/1473[(1) Heads up: breaking changes in 0.13.x · Issue #1473 · metallb/metallb^]
*** https://www.nic.ad.jp/ja/translation/rfc/1918.html[RFC1918 日本語訳^]
** L2関連
*** https://metallb.universe.tf/configuration/_advanced_l2_configuration/[MetalLB > ADVANCED L2 CONFIGURATION^]

== Start/Stop

. Start a docker service
+
[source,shell]
----
sudo service docker start
----

== Build & deploy apps

. Build a image
+
[source,shell]
----
docker image build --tag greet-go:0.1 -f Dockerfile-MultiStage .
----

* Push image to kind
+
[source,shell]
----
kind --name kind-1 load docker-image greet-go:0.1
----
+
[source,console,subs="quotes"]
----
$ docker container ls --format "table {{.Image}}\t{{.State}}\t{{.Names}}"
IMAGE                  STATE     NAMES
kindest/node:v1.24.0   running   kind-1-control-plane
$ docker exec -it kind-1-control-plane crictl images
IMAGE                                      TAG                  IMAGE ID            SIZE
docker.io/kindest/kindnetd                 v20221004-44d545d1   d6e3e26021b60       25.8MB
docker.io/kindest/local-path-helper        v20220607-9a4d8d2a   d2f902e939cc3       2.86MB
docker.io/kindest/local-path-provisioner   v0.0.22-kind.0       4c1e997385b8f       17.4MB
docker.io/library/greet-go                 0.1                  abd18c430d5ec       12.5MB
quay.io/metallb/controller                 v0.13.7              e73361dabfb86       25.6MB
quay.io/metallb/speaker                    v0.13.7              738c5d221d601       46.9MB
registry.k8s.io/coredns/coredns            v1.9.3               5185b96f0becf       14.8MB
registry.k8s.io/etcd                       3.5.4-0              a8a176a5d5d69       102MB
registry.k8s.io/kube-apiserver             v1.25.3              4bc1b1e750e34       76.5MB
registry.k8s.io/kube-controller-manager    v1.25.3              580dca99efc3b       64.5MB
registry.k8s.io/kube-proxy                 v1.25.3              86063cd68dfc9       63.3MB
registry.k8s.io/kube-scheduler             v1.25.3              5225724a11400       51.9MB
registry.k8s.io/pause                      3.7                  221177c6082a8       311kB
----

. Tests
+
[source,console]
----
$ docker container exec -it kind-1-control-plane curl http://10.244.0.7:8080/api/greet/John
{"message":"Hello, world!"}
----

=== Deploy using Pod

. Deploy apps to kind
+
[source,yaml]
.kind/greet-go.pod.yaml
----
apiVersion: v1
kind: Pod
metadata:
  name: greet-go-pod
  labels:
    app: greet-go-app
spec:
  containers:
  - name: greet-go
    image: greet-go:0.1
    imagePullPolicy: Never
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: greet-go-service
spec:
  type: LoadBalancer
  selector:
    app: greet-go-app
  ports:
    - name: http
      port: 3000
      targetPort: 8080
      protocol: TCP
----
+
[source,console]
----
$ kubectl apply -f kind/greet-go.pod.yaml
pod/greet-go-pod created
service/greet-go-service created
----

. Check results
+
[source,console]
----
$ kubectl get services greet-go-service
NAME               TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)          AGE
greet-go-service   LoadBalancer   10.96.229.58   172.18.254.240   3000:30466/TCP   35s
----

** Selectorの設定が正しい場合は次のように Service に Endpoint が自動的に作成される
+
[source,console]
----
$ kubectl get endpoints greet-go-service
NAME               ENDPOINTS          AGE
greet-go-service   10.244.0.31:8080   56s
----

** Service に対する Endpoint が作成済みであれば arp の HWaddress の項目に MACアドレスが入る
+
[source,console]
----
$ arp $(kubectl get services greet-go-service -o jsonpath='{.status.loadBalancer.ingress[*].ip}')
Address                  HWtype  HWaddress           Flags Mask            Iface
172.18.254.240           ether   02:42:ac:12:00:02   C                     br-cb34625844b6
----

. Send test request

** Get response of curl through POD IP address
+
[source,console]
----
$ docker container exec -it kind-1-control-plane curl http://$(kubectl get pod greet-go-pod -o jsonpath='{.status.podIP}'):8080/api/greet/John | python3 -m json.tool
{
    "message": "Hello, John!"
}
----

** Accessing Pods through internal DNS with Pod IP
+
[source,console]
----
$ kubectl get pods -l app=greet-go-app -o custom-columns="Pod IP":.status.podIP,"Container port":.spec.containers[0].ports[].containerPort
Pod IP        Container port
10.244.0.31   8080
$ kubectl run -q -n default -it curl --image=curlimages/curl --rm --restart=Never --wait=true -- -s -L http://10-244-0-31.greet-go-service.default.svc.cluster.local:8080/api/greet/John | python3 -m json.tool
{
    "message": "Hello, John!"
}
----

** Accessing Pods through internal DNS with Service Name
+
[source,console]
----
$ kubectl get services greet-go-service
NAME               TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)          AGE
greet-go-service   LoadBalancer   10.96.229.58   172.18.254.240   3000:30466/TCP   11m
$ docker container exec -it kind-1-control-plane curl http://greet-go-service.default.svc.cluster.local:3000/api/greet/John
curl: (6) Could not resolve host: greet-go-service.default.svc.cluster.local
$ kubectl run -q -n default -it curl --image=curlimages/curl --rm --restart=Never --wait=true -- -s -L http://greet-go-service.default.svc.cluster.local:3000/api/greet/John | python3 -m json.tool
{
    "message": "Hello, John!"
}
----

** Forward a local port to a port on the Pod
+
[source,console]
----
$ kubectl get pods
NAME           READY   STATUS    RESTARTS   AGE
greet-go-pod   1/1     Running   0          4m52s
----
+
[source,console]
----
$ kubectl port-forward greet-go-pod 3000:8080
Forwarding from 127.0.0.1:3000 -> 8080
Forwarding from [::1]:3000 -> 8080
...
----
+
Open a new terminal and run the following command:
+
[source,console]
----
$ curl -s http://localhost:3000/api/greet/John \
> --header "Content-Type: application/json" --request "GET" | python3 -m json.tool
{
    "message": "Hello, John!"
}
----

** Using External IP
+
[source,console]
----
$ kubectl get services greet-go-service
NAME               TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)          AGE
greet-go-service   LoadBalancer   10.96.229.58   172.18.254.240   3000:30466/TCP   6m33s
----
+
[source,console]
----
$ curl -s http://172.18.254.240:3000/api/greet/John \
--header "Content-Type: application/json" --request "GET" | python3 -m json.tool
{
    "message": "Hello, John!"
}
$ curl -s http://$(kubectl get services greet-go-service -o jsonpath='{.status.loadBalancer.ingress[*].ip}'):$(kubectl get services greet-go-service -o jsonpath='{.spec.ports[0].port}')/api/greet/John --header "Content-Type: application/json" | python3 -m json.tool
{
    "message": "Hello, John!"
}
----

. Delete deployments
+
[source,shell]
----
kubectl delete -f kind/greet-go.pod.yaml
----
+
[source,console]
----
$ kubectl delete -f kind/greet-go.pod.yaml
pod "greet-go-pod" deleted
service "greet-go-service" deleted
----

=== Deploy using Deployment

. Deploy apps to kind
+
[source,yaml]
.kind/greet-go.deployment.yaml
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greet-go-app
spec:
  selector:
    matchLabels:
      app: greet-go-app
  replicas: 2
  template:
    metadata:
      labels:
        app: greet-go-app
    spec:
      containers:
      - name: greet-go
        image: greet-go:0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: greet-go-service
spec:
  type: LoadBalancer
  selector:
    app: greet-go-app
  ports:
    - name: http
      port: 3000
      targetPort: 8080
      protocol: TCP
----
+
[source,console]
----
$ kubectl apply -f kind/greet-go.deployment.yaml
deployment.apps/greet-go-app created
service/greet-go-service created
----
+
[source,console]
----
$ kubectl get deployments
NAME           READY   UP-TO-DATE   AVAILABLE   AGE
greet-go-app   2/2     2            2           10m
$ kubectl get pods -l app=greet-go-app
NAME                            READY   STATUS    RESTARTS   AGE
greet-go-app-78cc5cfdd8-aaaaa   1/1     Running   0          10m
greet-go-app-78cc5cfdd8-bbbbb   1/1     Running   0          10m
$ kubectl get services
NAME               TYPE           CLUSTER-IP    EXTERNAL-IP      PORT(S)          AGE
greet-go-service   LoadBalancer   10.96.94.74   172.18.254.240   3000:30485/TCP   11m
kubernetes         ClusterIP      10.96.0.1     <none>           443/TCP          59m
$ kubectl get endpoints
NAME               ENDPOINTS                         AGE
greet-go-service   10.244.0.6:8080,10.244.0.7:8080   11m
kubernetes         172.18.0.2:6443                   59m
$ arp
Address                  HWtype  HWaddress           Flags Mask            Iface
172.18.0.2               ether   02:42:ac:12:00:02   C                     br-cb34625844b6
DESKTOP-E39V4F4          ether   00:15:5d:ba:d9:2c   C                     eth0
----

. Send test request

** Get response of curl through POD IP address
+
[source,console]
----
$ kubectl get pods -l app=greet-go-app -o custom-columns="Pod IP":
.status.podIP,"Container port":.spec.containers[0].ports[].containerPort
Pod IP       Container port
10.244.0.7   8080
10.244.0.6   8080
----
+
[source,console]
----
$ kubectl get pods -l app=greet-go-app -o name | sed -e 's@pod/@@' | while read POD_NAME;do (set -x; POD_IP=$(kubectl get pod ${POD_NAME} -o jsonpath='{.status.podIP}'); docker container exec kind-1-control-plane curl -s http://${POD_IP}:8080/api/greet/John ); echo; done
++ kubectl get pod greet-go-app-6cf496f84c-aaaaa -o 'jsonpath={.status.podIP}'
+ POD_IP=10.244.0.12
+ docker container exec kind-1-control-plane curl -s http://10.244.0.12:8080/api/greet/John
{"message":"Hello, world!"}
++ kubectl get pod greet-go-app-6cf496f84c-bbbbb -o 'jsonpath={.status.podIP}'
+ POD_IP=10.244.0.13
+ docker container exec kind-1-control-plane curl -s http://10.244.0.13:8080/api/greet/John
{"message":"Hello, world!"}
----

** Accessing Pods through internal DNS with Pod IP
+
[source,console]
----
$ kubectl run -q -n default -it curl --image=curlimages/curl --rm --restart=Never --wait=true -- -s -L http://10-244-0-6.greet-go-service.default.svc.cluster.local:8080/api/greet/John | python3 -m json.tool
{
    "message": "Hello, John!"
}
$ kubectl run -q -n default -it curl --image=curlimages/curl --rm --restart=Never --wait=true -- -s -L http://10-244-0-7.greet-go-service.default.svc.cluster.local:8080/api/greet/John | python3 -m json.tool
{
    "message": "Hello, John!"
}
----

** Accessing Pods through internal DNS with Service Name
+
[source,console]
----
$ kubectl get services greet-go-service
NAME               TYPE           CLUSTER-IP    EXTERNAL-IP      PORT(S)          AGE
greet-go-service   LoadBalancer   10.96.94.74   172.18.254.240   3000:30485/TCP   65m
$ docker container exec -it kind-1-control-plane curl http://greet-go-service.default.svc.cluster.local:3000/api/greet/John
curl: (6) Could not resolve host: greet-go-service.default.svc.cluster.local
$ kubectl run -q -n default -it curl --image=curlimages/curl --rm --restart=Never --wait=true -- -s -L http://greet-go-service.default.svc.cluster.local:3000/api/greet/John | python3 -m json.tool
{
    "message": "Hello, John!"
}
----

** Forward a local port to a port on the Pod
+
[source,console]
----
$ kubectl get pods -l app=greet-go-app
NAME                            READY   STATUS    RESTARTS   AGE
greet-go-app-6cf496f84c-aaaaa   1/1     Running   0          32m
greet-go-app-6cf496f84c-bbbbb   1/1     Running   0          32m
----
+
[source,console]
----
$ kubectl port-forward greet-go-app-6cf496f84c-aaaaa 3000:8080
Forwarding from 127.0.0.1:3000 -> 8080
Forwarding from [::1]:3000 -> 8080
Handling connection for 3000
...
----
+
Open a new terminal and run the following command:
+
[source,console]
----
$ curl -s http://localhost:3000/api/greet/John \
--header "Content-Type: application/json" --request "GET" | python3 -m json.tool
{
    "message": "Hello, John!"
}
----
+
[source,console]
----
$ kubectl port-forward greet-go-app-6cf496f84c-bbbbb 3000:8080
Forwarding from 127.0.0.1:3000 -> 8080
Forwarding from [::1]:3000 -> 8080
...
----
+
Open a new terminal and run the following command:
+
[source,console]
----
$ curl -s http://localhost:3000/api/greet/John \
--header "Content-Type: application/json" --request "GET" | python3 -m json.tool
{
    "message": "Hello, John!"
}
----

** Using External IP
+
[source,console]
----
$ kubectl get services
NAME               TYPE           CLUSTER-IP    EXTERNAL-IP      PORT(S)          AGE
greet-go-service   LoadBalancer   10.96.94.74   172.18.254.240   3000:30485/TCP   17m
kubernetes         ClusterIP      10.96.0.1     <none>           443/TCP          65m
----
+
----
$ curl -s http://172.18.254.240:3000/api/greet/John \
--header "Content-Type: application/json" --request "GET" | python3 -m json.tool
{
    "message": "Hello, John!"
}
$ curl -s http://$(kubectl get services greet-go-service -o jsonpath='{.status.loadBalancer.ingress[*].ip}'):$(kubectl get services greet-go-service -o jsonpath='{.spec.ports[0].port}')/api/greet/John --header "Content-Type: application/json" | python3 -m json.tool
{
    "message": "Hello, John!"
}
----

. Delete deployments
+
[source,shell]
----
kubectl delete -f kind/greet-go.deployment.yaml
----
+
[source,console]
----
$ kubectl delete -f kind/greet-go.deployment.yaml
deployment.apps "greet-go-app" deleted
service "greet-go-service" deleted
----

=== Deploy using deployment with loadBalancerIP

. Make sure the EXTERNAL-IP value is `<none>`
+
[source,console]
----
$ kubectl get services
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   15m
----

. Deploy a app
+
[source,yaml]
.greet-go-app.loadBalancerIP.yaml
----
apiVersion: v1
kind: Service
metadata:
  name: greet-go-app-metallb
spec:
  type: LoadBalancer
  loadBalancerIP: 172.18.0.240 # <1>
  selector:
    app: greet-go-app
  ports:
    - name: http
      port: 8080
      targetPort: 808
----
<1> Set EXTERNAL IP

. Make sure the EXTERNAL-IP value is "172.18.255.240".
+
[source,console]
----
$ kubectl apply -f greet-go-pod.service.yaml
service/greet-go-pod-metallb created
$ kubectl get services
NAME                   TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)          AGE
greet-go-pod-metallb   LoadBalancer   10.96.78.233   172.18.255.240   8080:30213/TCP   3m4s
kubernetes             ClusterIP      10.96.0.1      <none>           443/TCP          21m
----

. Tests
+
[source,console]
----
$ curl -s http://172.18.0.240:8080/api/greet/John --header "Content-Type: application/json"
{"message":"Hello, world!"}
----

== Storage

=== Persistent Volumes

* https://mauilion.dev/posts/kind-pvc/[Kind Persistent Volumes | mauilion.dev^] +
  kind persistent volume - Search
* https://stackoverflow.com/questions/62694361/how-to-reference-a-local-volume-in-kind-kubernetes-in-docker[How to reference a local volume in Kind (kubernetes in docker) - Stack Overflow^] +
  k8s kind persistent volume - Search

== References

* https://blog.framinal.life/entry/2020/04/16/022042[【手順あり】MetalLBの使い方から動きまで解説します - フラミナル^] 
* https://docs.microsoft.com/en-us/windows/wsl/networking[Accessing network applications with WSL | Microsoft Docs^]
* https://zenn.dev/solufa/articles/accessing-wsl2-from-mobile[WSL2で開発中のWebアプリを同じLANのスマホで動作確認する方法^]
