ifndef::leveloffset[]
:toc: left
:toclevels: 3

ifndef::env-github[]
:icons: font
endif::[]

ifdef::env-github[]
// Alternative to :icons: font on GitHub.
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

ifndef::imagesdir[]
:imagesdir: images
endif::[]

include::header.adoc[]

endif::[]

== prometheus-community

=== Install prometheus-community Helm Charts

.References
* https://github.com/prometheus-community/helm-charts[GitHub - prometheus-community/helm-charts: Prometheus community Helm charts^]
** https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/README.md[helm-charts/charts/kube-prometheus-stack/README.md at main · prometheus-community/helm-charts · GitHub^]
* https://grafana.com/docs/grafana/latest/setup-grafana/installation/helm/[Deploy Grafana using Helm Charts | Grafana documentation^]

. Add the Helm repository
+
[source,shell]
----
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
----

. Run the following command to verify the repository was added:
+
[source,shell]
----
helm repo list
----

. Run the following command to update the repository to download the latest Prometheus and Grafana Helm charts:
+
[source,shell]
----
helm repo update
----

. To create a namespace, run the following command:
+
[source,shell]
----
kubectl create ns "${NAMESPACE_PROMETHEUS:-prometheus-grafana}" --dry-run=client -o yaml | kubectl apply -f -
----

. (Optional)Verify diff
+
[source,shell]
----
MY_RELEASE_NAME="${MY_RELEASE_NAME:-prometheus-grafana}"
NAMESPACE_PROMETHEUS="${NAMESPACE_PROMETHEUS:-prometheus-grafana}"
helm list -n "${NAMESPACE_PROMETHEUS}"
helm diff upgrade --install "${MY_RELEASE_NAME}" prometheus-community/kube-prometheus-stack --namespace "${NAMESPACE_PROMETHEUS}"
----

. Run the following command to deploy the Prometheus Helm Chart inside your namespace.
+
[source,shell]
----
MY_RELEASE_NAME="${MY_RELEASE_NAME:-prometheus-grafana}"
NAMESPACE_PROMETHEUS="${NAMESPACE_PROMETHEUS:-prometheus-grafana}"
helm upgrade --install prometheus prometheus-community/kube-prometheus-stack --namespace "${NAMESPACE_PROMETHEUS}" --create-namespace -f ./values.yaml
----

. To view all the Kubernetes components installed, run kubectl get all command. 
+
[source,shell]
----
NAMESPACE_PROMETHEUS="${NAMESPACE_PROMETHEUS:-prometheus-grafana}"
kubectl get -n "${NAMESPACE_PROMETHEUS}" all
----

. Use the following command to check the connection to the Grafana server. +
See: https://grafana.com/docs/grafana/latest/developers/http_api/other/[Other HTTP API | Grafana documentation^]
+
[source,shell]
----
NAMESPACE_PROMETHEUS="${NAMESPACE_PROMETHEUS:-prometheus-grafana}"
NAMESPACE_GRAFANA="${NAMESPACE_GRAFANA:-prometheus-grafana}"
GRAFANA_TOKEN=$(kubectl get --namespace "${NAMESPACE_GRAFANA}" secret/prometheus-grafana -o go-template='{{index .data "admin-user" | base64decode}}{{":"}}{{index .data "admin-password" | base64decode}}{{"\n"}}')
kubectl run -q -n "${NAMESPACE:-default}" -it curl --image=curlimages/curl --rm --restart=Never -- -s -L http://prometheus-grafana.${NAMESPACE_PROMETHEUS}.svc.cluster.local:80/api/health -H "Accept: application/json" --user ${GRAFANA_TOKEN}
----

. Get Grafana 'admin' user password by running:
+
[source,shell]
----
kubectl get --namespace "${NAMESPACE_GRAFANA:-prometheus-grafana}" secret/prometheus-grafana -o go-template='{{range $k,$v := .data}}{{printf "%s: " $k}}{{if not $v}}{{$v}}{{else}}{{$v | base64decode}}{{end}}{{"\n"}}{{end}}'
----

. The Grafana server can be accessed via port 80 on the following DNS name from within your cluster:
+
[source,shell]
----
kubectl port-forward --namespace ${NAMESPACE_GRAFANA:-prometheus-grafana} $(kubectl get pods --namespace ${NAMESPACE_GRAFANA:-prometheus-grafana} -l "app.kubernetes.io/name=grafana" -o jsonpath="{.items[0].metadata.name}") 3000
----

=== Uninstall prometheus-community Helm Charts

. Run the following command to deploy the Prometheus Helm Chart inside your namespace.
+
[source,shell]
----
MY_RELEASE_NAME="${MY_RELEASE_NAME:-prometheus-grafana}"
NAMESPACE_PROMETHEUS="${NAMESPACE_PROMETHEUS:-prometheus-grafana}"
helm uninstall --namespace "${NAMESPACE_PROMETHEUS}" prometheus
----

== prometheus-operator

=== Install prometheus-operator

https://grafana.com/docs/grafana-cloud/monitor-infrastructure/kubernetes-monitoring/configuration/configure-infrastructure-manually/prometheus/prometheus-operator/[Install Prometheus Operator with Grafana Cloud for Kubernetes | Grafana Cloud documentation]

[source,shell]
----
NAMESPACE_PROMETHEUS=${NAMESPACE_PROMETHEUS:-prometheus}
kubectl create ns "${NAMESPACE_PROMETHEUS:-prometheus}" --dry-run=client -o yaml | kubectl apply -f -
kubectl create --namespace="${NAMESPACE_PROMETHEUS:-prometheus}" -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/master/bundle.yaml
----
