version: "3.7"

services:
  postgres:
    restart: always
    image: postgres:14-alpine
    container_name: postgres-noschema
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - type: bind
        source: "./initdb.d"
        target: "/docker-entrypoint-initdb.d"
      - /var/tmp/postgres-noschema/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d fruits -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
