CREATE DATABASE fruits;

CREATE OR REPLACE ROLE user_role;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER ON *.* TO user_role WITH GRANT OPTION;

USE fruits;
CREATE TABLE fruits_menu (id SERIAL PRIMARY KEY, name VARCHAR(16) UNIQUE, price INTEGER, quantity INTEGER DEFAULT 0, mod_time timestamp DEFAULT current_timestamp);
INSERT INTO fruits_menu (name, price, quantity) VALUES ('Apple', 100, 10), ('Banana', 120, 1), ('Orange', 110, 0);
