apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-task
  labels:
    app: hello-tekton-task
spec:
  steps:
  - name: greetings
    image: alpine
    script: |
      #!/bin/sh
      date
      echo "Hello world"
