apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-html-app
spec:
  selector:
    matchLabels:
      app: static-html-app
  replicas: 2
  template:
    metadata:
      labels:
        app: static-html-app
    spec:
      containers:
      - name: server
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html/"
          name: nginx-html-volume
          readOnly: true
        - mountPath: "/usr/share/nginx/html/css"
          name: nginx-html-css-volume
          readOnly: true
      volumes:
      - name: nginx-html-volume
        configMap:
          name: nginx-html
      - name: nginx-html-css-volume
        configMap:
          name: nginx-html-css
