---
apiVersion: v1
kind: Service
metadata:
  name: static-html-service
  namespace: demo
spec:
  type: LoadBalancer
  selector:
    app: static-html-app
  ports:
    - name: http
      port: 3000
      targetPort: 80
      protocol: TCP
