---
apiVersion: v1
kind: Service
metadata:
  name: static-html-service
spec:
  type: LoadBalancer
  selector:
    app: static-html-app      # This field will be replaced by the kustomize.
  ports:
    - name: http
      port: 3000
      targetPort: 80
      protocol: TCP
