== Postgresql

=== Setup

. Create a `.env` file for docker-compose.
+
[source,shell]
.env
----
POSTGRES_USER=postgres
POSTGRES_PASSWORD=:********
ADDITIONAL_USER=dbuser1
ADDITIONAL_PASSWORD=:********
----

. (Optional) Install postgresql client.
+
[source,shell]
----
sudo apt-cache search postgresql | grep postgresql
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt -y update
sudo apt -y install postgresql-client-14
----

. (Optional) Create a .pgpass file for your local psql installation.
+
[source,plaintext]
.~/.pgpass
----
localhost:5432:fruits:postgres:********
localhost:5432:postgres:postgres:********
----
+
[source,console]
----
$ chmod 600 ~/.pgpass
----

=== Manage container

* Start a container
+
[source,shell]
----
docker-compose up -d
----

* Stop a container
+
----
docker-compose down
----

* Show logs in container
+
[source,shell]
----
docker logs postgres-dbuser1
----

* Debug a container
+
[source,shell]
----
docker exec -it postgres-dbuser1 /bin/bash
----

=== Create database and tables

* Create database and schema
+
[source,sql]
----
CREATE ROLE dbuser1 LOGIN PASSWORD '********';
CREATE DATABASE fruits;
\connect fruits;
CREATE SCHEMA IF NOT EXISTS dbuser1;
GRANT USAGE ON SCHEMA dbuser1 TO dbuser1;
----

* Create table and insert records.
+
[source,sql]
----
\connect fruits;
SET SCHEMA 'dbuser1';

CREATE TABLE fruits_menu (
  id SERIAL PRIMARY KEY,
  name VARCHAR(16) UNIQUE,
  price INTEGER,
  mod_time timestamp DEFAULT current_timestamp
);

GRANT SELECT,INSERT,UPDATE,DELETE ON fruits_menu TO dbuser1;
GRANT USAGE ON SEQUENCE fruits_menu_id_seq TO dbuser1;

INSERT INTO fruits_menu (name, price) VALUES
  ('Apple', 100), ('Banana', 120), ('Orange', 110);
----

* Show tables
+
[source,console]
----
$ psql -h localhost -U dbuser1 -d fruits
fruits=> SELECT * FROM pg_catalog.pg_tables WHERE tablename='fruits_menu';
 schemaname |  tablename  | tableowner | tablespace | hasindexes | hasrules | hastriggers | rowsecurity
------------+-------------+------------+------------+------------+----------+-------------+-------------
 dbuser1    | fruits_menu | postgres   |            | t          | f        | f           | f
(1 row)

fruits=> \d
Did not find any relations.

fruits=> \dt dbuser1.fruits_menu;
            List of relations
 Schema  |    Name     | Type  |  Owner
---------+-------------+-------+----------
 dbuser1 | fruits_menu | table | postgres
(1 row)

fruits=> \dn+ dbuser1
                     List of schemas
  Name   |  Owner   |  Access privileges   | Description
---------+----------+----------------------+-------------
 dbuser1 | postgres | postgres=UC/postgres+|
         |          | dbuser1=U/postgres   |
(1 row)
----

* Show content of a table
+
[source,console]
----
$ psql -h localhost -U dbuser1 -d fruits -c "SET SCHEMA 'dbuser1'; SELECT * FROM fruits_menu;"
 id |  name  | price |          mod_time
----+--------+-------+----------------------------
  1 | Apple  |   100 | 2022-09-11 06:52:07.674135
  2 | Banana |   120 | 2022-09-11 06:52:07.674135
  3 | Orange |   112 | 2022-09-11 06:52:07.674135
(3 rows)

$ psql -h localhost -U dbuser1 -d fruits -c "SET search_path TO dbuser1;SELECT * FROM fruits_menu;"
 id |  name  | price |          mod_time
----+--------+-------+----------------------------
  1 | Apple  |   100 | 2022-09-11 06:52:07.674135
  2 | Banana |   120 | 2022-09-11 06:52:07.674135
  3 | Orange |   112 | 2022-09-11 06:52:07.674135
(3 rows)

$ psql -h localhost -U dbuser1 -d fruits -c "SELECT * FROM dbuser1.fruits_menu;"
 id |  name  | price |          mod_time
----+--------+-------+----------------------------
  1 | Apple  |   100 | 2022-09-11 06:52:07.674135
  2 | Banana |   120 | 2022-09-11 06:52:07.674135
  3 | Orange |   112 | 2022-09-11 06:52:07.674135
(3 rows)
----
